server:
  port: 8085

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categorias/**
          filters:
            - AuthFilter


        - id: ms-kajita-service
          uri: lb://ms-kajita-service
          predicates:
            - Path=/productos/**
          filters:
            - AuthFilter

        - id: ms-test01post-service
          uri: lb://ms-test01post-service
          predicates:
            - Path=/ventas/**
          filters:
            - AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-cliente-service-route
          uri: lb://ms-cliente-service
          predicates:
            - Path=/clientes/**
